### ISSUE TITLE
One of the logos in dark mode is not changing color

### ISSUE THREAD

**Issue by pnicto** [Divyateja04/divyateja04.github.io#10]
- Light mode 
![image](https://github.com/Divyateja04/divyateja04.github.io/assets/77240155/56f1afbe-53ff-4bab-8e30-ad0e8aca1e41)
- Dark mode 
![image](https://github.com/Divyateja04/divyateja04.github.io/assets/77240155/53a0bee8-ec1f-46ff-a522-b830b9b78647)

Browser: Microsoft Edge 122.0.2325.0 (Official build) dev (64-bit)

**Comment by Divyateja04** [comment]
fixed in new portfolio :)
